# yamllint disable rule:line-length
# yamllint disable rule:braces

name: CI

on:
    pull_request:
    push:
        branches:
            - "master"

jobs:
    phpunit:
        name: "PHPUnit"
        runs-on: "ubuntu-22.04"

        strategy:
            matrix:
                php-version:
                    - "8.1"
                    - "8.2"
                    - "8.3"
                    - "8.4"
                dependencies:
                    - "highest"
                include:
                    - php-version: "8.1"
                      dependencies: "lowest"

        steps:
            - name: "Checkout"
              uses: "actions/checkout@v4"
              with:
                  fetch-depth: 2

            - name: "Install PHP"
              uses: "shivammathur/setup-php@v2"
              with:
                  php-version: "${{ matrix.php-version }}"
                  coverage: xdebug
                  ini-values: "zend.assertions=1"

            - name: "Install dependencies with Composer"
              uses: "ramsey/composer-install@v3"
              with:
                  dependency-versions: "${{ matrix.dependencies }}"

            - name: "Run PHPUnit"
              run: "vendor/bin/phpunit"
