name: "Static Analysis"

on:
    pull_request:
    push:
        branches:
            - "master"

jobs:
    static-analysis-phpstan:
        name: "Static Analysis with PHPStan"
        runs-on: "ubuntu-22.04"

        strategy:
            fail-fast: false
            matrix:
                php-version:
                    - "8.1"
                    - "8.2"
                    - "8.3"
                    - "8.4"

        steps:
            -   name: "Checkout code"
                uses: "actions/checkout@v4"

            -   name: "Install PHP"
                uses: "shivammathur/setup-php@v2"
                with:
                    coverage: "none"
                    php-version: "${{ matrix.php-version }}"
                    tools: "cs2pr"

            -   name: "Install dependencies with Composer"
                uses: "ramsey/composer-install@v3"
                with:
                    composer-options: "${{ matrix.composer-options }}"

            -   name: "Run a static analysis with phpstan/phpstan"
                run: "vendor/bin/phpstan analyse --error-format=checkstyle | cs2pr"

            -   name: "Run a static analysis with rector/rector"
                run: "vendor/bin/rector --dry-run"
                if: ${{ matrix.php-version == 8.4 }}
